# Generated by Django 4.2.20 on 2025-04-14 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='term_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='glossary.category')),
            ],
        ),
        migrations.CreateModel(
            name='TermDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='term_details/')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='glossary.term')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_description', models.TextField(blank=True, null=True)),
                ('related_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to_terms', to='glossary.term')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_terms', to='glossary.term')),
            ],
        ),
    ]
