# Generated by Django 4.2.20 on 2025-05-10 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='ProfessionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_about_profession', models.TextField()),
                ('video_about_profession', models.URLField(blank=True, null=True)),
                ('quote_about_path', models.TextField()),
                ('video_about_path', models.URLField(blank=True, null=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='glossary.term')),
            ],
        ),
    ]
