# Generated by Django 4.2.20 on 2025-06-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_alter_term_options_professionrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedterm',
            name='related_term',
        ),
        migrations.AddField(
            model_name='relatedterm',
            name='related_terms',
            field=models.ManyToManyField(related_name='related_to', to='glossary.term'),
        ),
        migrations.AlterField(
            model_name='professionrecommendation',
            name='video_about_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionrecommendation',
            name='video_about_profession',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatedterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='glossary.term'),
        ),
    ]
