# Generated by Django 4.2.20 on 2025-06-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0004_remove_relatedterm_related_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionrecommendation',
            name='roadmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='roadmaps/'),
        ),
    ]
